modLoader="javafml"
loaderVersion="[52,)"
license="${mod_license}"
issueTrackerURL="https://github.com/CosmicPhoenix171/EnchantmentMastery/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
