modLoader="javafml"
loaderVersion="[52,)"
license="MIT"
issueTrackerURL="https://github.com/CosmicPhoenix171/EnchantmentMastery/issues"

[[mods]]
modId="enchantmentmastery"
version="${mod_version}"
displayName="Enchantment Mastery"
authors="CosmicPhoenix171"
description='''A per-player Enchantment Mastery system with Standard Galactic Alphabet decoding.'''

[[mixins]]
config="enchantmentmastery.mixins.json"

[[dependencies.enchantmentmastery]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enchantmentmastery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
